version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_BUCKET: vehicles
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
    networks:
      - sim-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - sim-net
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulator
    depends_on:
      - influxdb
    networks:
      - sim-net
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: mytoken
      INFLUX_ORG: myorg
      INFLUX_BUCKET: vehicles

networks:
  sim-net:

volumes:
  influxdb-data:
  grafana-data:
